# .streamlit/secrets.toml  

[connections.snowflake]
account = "RGB60977"
user = "BEANSSNOWCERTS"
password = "https://app.sigmacomputing.com/interworks/workbook/workbook-4n2XiZq6qMH1oKUgE9ptIy?:link_source=share"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = 'PUBLIC"
client_session_keep_alive = true
