# .streamlit/secrets.toml  

[connections.snowflake]
account = "EMCDJUJ-RGB60977"
user = "BEANSSNOWCERTS"
password = "ueq_kvg4jcn4knu9PAM"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = 'PUBLIC"
client_session_keep_alive = true
